# .graphclientrc.yml
sources:
  - name: updraft
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/subgraphs/id/AX96zuXixk4ugPQG7CDypy1EdRnYE4Z9khjk2fpzHfAq
        schemaHeaders:
          Authorization: Bearer ${VITE_GRAPH_API_KEY}
        operationHeaders:
          Authorization: Bearer ${VITE_GRAPH_API_KEY}
documents:
  - ./src/features/**/queries/*.graphql